kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: config-file
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: config-file
    #       key: trainer
    envFrom:
    - configMapRef:
      name: config-file